version: '3.8'

services:
    cns-notification-api:
        image: 10.251.2.107:5000/notification-api:UAT-20240404-8c2d83eb
        container_name: cns-notification-api
        ports:
            - 3000:3000
        environment:
            - MONGODB_URI=mongodb://10.251.2.108:27017/CNS
            - RABBITMQ_URI=amqp://rabbitmq:5672
            - POSTGRES_HOST=10.251.2.109
            - POSTGRES_PORT=5432
            - POSTGRES_USER=ncp_schema
            - POSTGRES_PASSWORD=ncp_P&ddw*rd123
            - POSTGRES_DB=cns
        networks:
            - cm-network
    cns-worker-service:
        image: 10.251.2.107:5000/worker-service:UAT-20240404-8c2d83eb
        container_name: cns-worker-service
        ports:
            - 3010:3010
        environment:
            - MONGODB_URI=mongodb://10.251.2.108:27017/CNS
            - RABBITMQ_URI=amqp://rabbitmq:5672
            - POSTGRES_HOST=10.251.2.109
            - POSTGRES_PORT=5432
            - POSTGRES_USER=ncp_schema
            - POSTGRES_PASSWORD=ncp_P&ddw*rd123
            - POSTGRES_DB=cns
        networks:
            - cm-network
    cns-dlx-notification-api:
        image: 10.251.2.107:5000/dlx-notification-api:UAT-20240404-8c2d83eb
        container_name: cns-dlx-notification-api
        ports:
            - 3050:3050
        environment:
            - MONGODB_URI=mongodb://10.251.2.108:27017/CNS
            - RABBITMQ_URI=amqp://rabbitmq:5672
            - POSTGRES_HOST=10.251.2.109
            - POSTGRES_PORT=5432
            - POSTGRES_USER=ncp_schema
            - POSTGRES_PASSWORD=ncp_P&ddw*rd123
            - POSTGRES_DB=cns
        networks:
            - cm-network
    cns-user:
        image: 10.251.2.107:5000/cns-user:UAT-20240404-8c2d83eb
        container_name: cns-user
        ports:
            - 3070:3070
        environment:
            - MONGODB_URI=mongodb://10.251.2.108:27017/CNS
            - POSTGRES_HOST=10.251.2.109
            - POSTGRES_PORT=5432
            - POSTGRES_USER=ncp_schema
            - POSTGRES_PASSWORD=ncp_P&ddw*rd123
            - POSTGRES_DB=cns
            - PUBLIC_KEY_FILE=/run/secrets/publicKey
            - PRIVATE_KEY_FILE=/run/secrets/privateKey
            - JWT_SECRET_FILE=/run/secrets/secretKey
        secrets:
            - publicKey
            - privateKey
            - secretKey
        networks:
            - cm-network
    cns-notification-record:
        image: 10.251.2.107:5000/cns-notification-record:UAT-20240404-8c2d83eb
        container_name: cns-notification-record
        ports:
            - 3060:3060
        environment:
            - MONGODB_URI=mongodb://10.251.2.108:27017/CNS
            - POSTGRES_HOST=10.251.2.109
            - POSTGRES_PORT=5432
            - POSTGRES_USER=ncp_schema
            - POSTGRES_PASSWORD=ncp_P&ddw*rd123
            - POSTGRES_DB=cns
            - PUBLIC_KEY_FILE=/run/secrets/publicKey
            - PRIVATE_KEY_FILE=/run/secrets/privateKey
            - JWT_SECRET_FILE=/run/secrets/secretKey
        secrets:
            - publicKey
            - privateKey
            - secretKey
        networks:
            - cm-network
        volumes:
            - /var/opt/cns-cm/secret:/run/secrets
    rabbitmq:
        image: 10.251.2.107:5000/rabbitmq:3.12-management
        container_name: rabbitmq
        ports:
            - 15672:15672
            - 5672:5672
        networks:
            - cm-network
secrets:
    publicKey:
        file: ./secrets/public.pem
    privateKey:
        file: ./secrets/private.pem
    secretKey:
        file: ./secrets/jwt.txt
networks:
    cm-network:
        driver: bridge
