### Email
POST http://localhost:5000/api/v1/notification-api/email 
content-type: application/json

{
    "from": "Jameslee@gmail.com",
    "to": "CM@gmail.com",
    "cc": "dacheng@gmail.com",
    "bcc": "titusLow@gmail.com",
    "subject": "promotion!",
    "body": "Salary increment to 1 million dollar",
    "template": 3
}
### SMS
POST http://localhost:5000/api/v1/notification-api/SMS 
content-type: application/json

{
    "sender": "92208810",
    "recipient": "+6592208810",
    "message": "hello world!"
}